language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  # replace existing curl with the PPA one
  # installing system zsync to get zsyncmake command until zsyncmake2 is ready
  - sudo apt-get -y install git cmake g++ libcurl3-gnutls-dev zsync

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake .. -DBUILD_CPR_TESTS=OFF -DUSE_SYSTEM_CURL=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - mkdir AppDir
  - make -j$(nproc) install DESTDIR=AppDir
  - mkdir -p AppDir/usr/share/{applications,icons/hicolor}
  - cp ../resources/zsync2.desktop AppDir/usr/share/applications
  - cp ../resources/zsync2.png AppDir/usr/share/icons/hicolor
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod +x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/zsync2.desktop -bundle-non-qt-libs
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x appimagetool-x86_64.AppImage
  - rm -rf AppDir/usr/include
  - find AppDir -type f -iname '*.a' -delete
  - find AppDir -type f -iname 'libssl*.so' -delete
  - find AppDir -type f -iname 'libcrypt*.so' -delete
  - ./appimagetool-x86_64.AppImage AppDir zsync2-x86_64.AppImage

after_success:
  - ls -lh build/
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh build/zsync2*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
